Update Chinese localization
loot/loot pull request #1486
Opened 2021-04-14 17:49 UTC by silentdark

Update Chinese localization

2021-04-14 17:55 UTC, sibir-ine commented
@silentdark Thank you so much! If you don't mind, there are also some masterlist messages that need to be translated to Chinese. You can read more at https://github.com/loot/loot.github.io/issues/77, but, basically, we have a spreadsheet that you can fill out so you don't have to worry about making PRs to all the masterlists. You can join our [Discord](https://loot.github.io/discord/) to download it, or we can provide you with a copy.

2021-04-14 17:57 UTC, sibir-ine commented
Also, since this is for LOOT v0.16.0, would you mind updating that in the translation file's properties?

2021-04-15 12:55 UTC, silentdark commented
Okay, it has been changed to LOOT v0.16.0, and then I also downloaded the localization file of masterlists.

2021-04-15 13:42 UTC, sibir-ine approved these changes
@silentdark Thank you so much! We also have a translator role that you can apply for in #role-registration in the Discord if you'd like to be notified when we need new translations.

2021-04-15 19:01 UTC, Ortham requested changes
Just the one change needed, thanks.

2021-04-16 03:36 UTC, silentdark commented on resources/l10n/zh_CN/LC_MESSAGES/loot.po
> +msgstr "错误: --自动排序已经完成但是没有 --提供游戏参数。"
Got it.

2021-04-16 03:37 UTC, sibir-ine commented on resources/l10n/zh_CN/LC_MESSAGES/loot.po
> +msgstr "Error: --auto-sort was passed but no --game parameter was provided."
@silentdark Only `--auto-sort` & `--game` need to stay untranslated. The rest of the sentence can be translated.

2021-04-16 03:51 UTC, sibir-ine requested changes
@silentdark 4ee8ab2f6c83036a304cd8c01742b58d952d9b4e needs to be reverted (or the files restored).

2021-04-16 04:00 UTC, silentdark commented
> @silentdark [4ee8ab2](https://github.com/loot/loot/commit/4ee8ab2f6c83036a304cd8c01742b58d952d9b4e) needs to be reverted (or the files restored).

Sorry, the new gitgub has changed so much that I am not used to it yet.

2021-04-16 04:03 UTC, sibir-ine approved these changes
> Sorry, the new gitgub has changed so much that I am not used to it yet.

No worries, thank you so much for your translations!

2021-04-17 07:48 UTC, Ortham approved these changes

2021-04-17 07:49 UTC, merged