Spanish translation
loot/loot pull request #1515
Opened 2021-05-29 21:48 UTC by Allen1351

2021-05-30 07:15 UTC, sibir-ine reviewed
@Allen1351 I've made comments for some errors I caught. Some can be committed from here, but a few will need manual corrections.

Also, loot.mo is unnecessary & should be deleted (LOOT builds it from loot.po already). You can prevent Poedit from generating one by going to `File` -> `Preferences...` -> `General` -> `Editing` -> `Automatically compile MO file when saving` & deselect it.

You should also go to `Catalog` -> `Properties` -> `Translation properties` -> `Project name and version:` & change that to `LOOT v0.16.1` since that's the current version of LOOT.

Finally, if you want, you can also go to `File` -> `Preferences...` -> `General` -> `Information about the translator` & enter a name/alias &/or an email that you'd like to be contacted by in case we or future translators have trouble reaching out to you. It's not necessary, but we'd appreciate it.

2021-05-31 12:11 UTC, sibir-ine reviewed
@Allen1351 I looked over the translation again & found a few more small issues, mostly with spaces & capitalization.

2021-05-31 12:11 UTC, sibir-ine commented on resources/l10n/es/LC_MESSAGES/loot.po
> +"3, Fallout: New Vegas, Fallout 4 and Fallout 4 VR."
This "and" can be translated.

2021-05-31 12:11 UTC, sibir-ine commented on resources/l10n/es/LC_MESSAGES/loot.po
> +msgstr "Revisión de la MasterList"
```suggestion
msgstr "Revisión de la Masterlist"
```

2021-05-31 12:11 UTC, sibir-ine commented on resources/l10n/es/LC_MESSAGES/loot.po
> +msgstr "Fecha de la MasterList"
```suggestion
msgstr "Fecha de la Masterlist"
```

2021-05-31 12:34 UTC, Ortham requested changes
I've gone through the translation and commited a couple of formatting fixes. sibir's found some that I missed though, so please resolve them too.

2021-06-01 09:16 UTC, merged