Update Ukrainian localization
loot/loot pull request #1779
Opened 2022-08-14 00:41 UTC by IllusiveMan196

2022-08-14 04:03 UTC, sibir-ine requested changes

2022-08-14 04:03 UTC, sibir-ine commented on resources/l10n/uk_UA/LC_MESSAGES/loot.po
> +msgstr "Приєднатися до серверу &Discord"
This is a Latin `D` as well, right? Is this also on a Cyrillic keyboard?

2022-08-14 19:20 UTC, IllusiveMan196 commented
As odd as it may be, but yes, both Latin and Cyrillic letters are on the
keyboard (unless it's some odd case where there is only one set, arguably
some keyboards have just baf execution of one or the other letter sets, so
despite having both technically... you have just one with good visibility).
Most shortcuts are also in Latin (courtesy of technology being made with
English-centric UI), so... technically doesn't really matter what key is
assigned to them.

As for mnemonics and & signs - feel free to redesignate them as I've
essentially played a game of "hope this letter isn't used anywhere else"
with them. Apparently not always successfully.

2022-08-15 09:47 UTC, sibir-ine commented
> As for mnemonics and & signs - feel free to redesignate them as I've essentially played a game of "hope this letter isn't used anywhere else" with them. Apparently not always successfully.

Re conflicting mnemonics, see https://github.com/loot/loot/pull/1778#issuecomment-1214810622 about how to tell if multiple conflict. Ideally, if the first character in a string has already been taken, the next most sensible character that hasn't also been taken would be used as opposed to any random character in the string, & that's not something we can really determine without being able to read Ukrainian. If you still have trouble assigning mnemonics without them conflicting we can try to guess at optimal assignments, but we'd appreciate it if you could give it another try first after I've hopefully clarified things. Also, you're always welcome to ask for further clarification if needed.

2022-08-15 17:43 UTC, Ortham commented
I've merged #1780 so if you merge/rebase you should now see comments in Poedit that tell you which strings appear in which menus, which should help avoid conflicts.

2022-08-16 04:02 UTC, sibir-ine commented on resources/l10n/uk_UA/LC_MESSAGES/loot.po
> +msgstr "&Скопіювати зміст"
This conflicts with `&Cортувати плагіни`. Anything other than `Г`, `C`, `П`, `А`, `К`, `Р`, `З`, `О`, `Д`, `В`, or `І` would be fine.

2022-08-18 03:52 UTC, sibir-ine commented on resources/l10n/uk_UA/LC_MESSAGES/loot.po
> +msgstr "&Копіювати метадані"
This now conflicts with `&Копіювати назву плагіну`. Anything other than `П`, `К`, `І`, `У`, or `Т` would be fine.

2022-08-18 03:52 UTC, sibir-ine commented on resources/l10n/uk_UA/LC_MESSAGES/loot.po
> +msgstr "Приєднатися до сер&веру Discord"
This now conflicts with `&Відкрити документацію`. Anything other than `Д`, `В`, `Р`, or any Latin characters would be fine.

2022-08-18 03:52 UTC, sibir-ine commented on resources/l10n/uk_UA/LC_MESSAGES/loot.po
> +msgstr "Знайти &картки..."
This still conflicts with `С&касувати відсортований порядок завантаження`. Anything other than `Г`, `І`, `П`, `У`, `К`, `Р`, `В`, `С`, `О`, `Е`, or `Ч` would be fine.

2022-08-18 03:52 UTC, sibir-ine commented on resources/l10n/uk_UA/LC_MESSAGES/loot.po
> +msgstr "&Виправити неоднозначний порядок завантаження"
This now conflicts with `Скопію&вати порядок завантаження`. Anything other than `Г`, `І`, `П`, `У`, `К`, `Р`, `В`, `С`, `О`, `Е`, or `Ч` would be fine.

2022-08-18 17:57 UTC, IllusiveMan196 commented
Improved, hopefully no collisions between symbols this time.

2022-08-19 02:28 UTC, sibir-ine approved these changes
Thanks! The mnemonics look good now.

2022-08-19 09:26 UTC, IllusiveMan196 commented
Note to myself - don't merge anything while PR is ongoing.

2022-08-19 09:32 UTC, sibir-ine commented
It's because you submitted a PR from your master branch. If you made a new branch specifically for your PR, you could sync it separately & only when needed. It'd also be easier to keep your master branch clean & even with the upstream branch.

2022-08-19 18:56 UTC, merged

2022-08-19 18:56 UTC, Ortham commented
Thanks 👍