User Warning to Morrowind Plugin Limit
loot/loot pull request #1803
Opened 2022-09-30 15:29 UTC by BraniganMatthew

Warns users exceeding the normal plugin limit for Morrowind, reminding them to not open the game without using the script extender.

2022-09-30 19:50 UTC, Ortham commented on src/gui/state/game/game.cpp
> +          "cause unaccountable damage to your game.")));
I'm a bit confused by the use of `unaccountable` here, I don't know what it's trying to communicate (though I'm not a Morrowind mod user, so maybe that's why). Does it mean that it won't obvious why things break when they do?

2022-10-01 07:33 UTC, Ortham commented
@BraniganMatthew am I right in thinking that this PR answers the question in my last comment in #1558?

2022-10-01 15:19 UTC, BraniganMatthew commented
@Ortham Sorry for the delay, this PR is my way of answering your question on that issue. I believe a warning is best for this problem because a user with that number of mods should know the risks of going past that 256 limit. Also, the word "unaccountable" is meant to describe severity.

2022-10-01 15:43 UTC, Ortham commented
@BraniganMatthew OK, thanks. Could you replace "unaccountable" with "severe"? I think that would be clearer, especially for ESL readers, and it would probably help translators too.

Otherwise, I think I'm happy to merge this.

2022-10-01 15:55 UTC, BraniganMatthew commented
@Ortham Ok just pushed that change

2022-10-02 11:30 UTC, Ortham requested changes

2022-10-02 11:30 UTC, Ortham commented on src/gui/state/game/game.cpp
> +          "More than 255 normal plugins are activated at the same time.");
I just spotted that the message says more than 255 but the check is for more than 254.

2022-10-02 14:02 UTC, BraniganMatthew commented
@Ortham I fixed the plugin count.

2022-10-02 14:05 UTC, Ortham approved these changes

2022-10-02 15:16 UTC, merged

2022-10-02 15:16 UTC, Ortham commented
Thanks!